server:
  port: 9000
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.zt.security.model
spring:
  application:
    name: security-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security_demo?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql8.0以前使用com.mysql.jdbc.Driver
    username: root
    password:
    platform: mysql
    #通过这句配置将druid连接池引入到我们的配置中，spring会尽可能判断类型是什么，然后根据情况去匹配驱动类。
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    root: info

